### ISSUE TITLE
Integrating cyclotron with an existing web app 

### ISSUE THREAD

**Issue by vribeiro-alexandre** [ExpediaInceCommercePlatform/cyclotron#21]
Hi.
I've just read the documentation and I have a question (although I didn't actually install it yet)...
**Would it be possible to integrate it with an existing app?** I mean, could I use it inside my own application just as a simple page?!

I suppose not since it's a node app, but I want to make sure before I start playing with it.

Thank you very much.

**Comment by baumandm** [comment]
Hi @vribeiro-alexandre, thanks for checking out the project.  Cyclotron is designed as a standalone website, rather than an embedded control or similar.  However, if you want to embed just the dashboard into another site I can think of two ideas:
1. You could either use an iframe to include the dashboard URL into another page.  I think the layout engine will work correctly in an iframe, but I don't think this scenario is well tested.
2. Use a webserver (e.g. Nginx) to proxy certain URLs from your website to the Cyclotron website.  By this I mean you could run your main website and Cyclotron separately, but rewrite a single URL from your main site to open a Cyclotron dashboard directly.

Not sure if either of these are what you want to do, but hopefully it's a start.

**Comment by vribeiro-alexandre** [comment]
Thanks a lot, @baumandm. The approach 1 would be the scenario closer than I was looking for because that way I would be able to have the same application layout for the dashboard, but I'm not sure if it'll be exactly what I expect. Anyway, I'll play with it as soon as I can.

Thank you very much.
