### ISSUE TITLE
Chart widget - numeric data "converted" to text, and then fails

### ISSUE THREAD

**Issue by JoachimL** [ExpediaInceCommercePlatform/cyclotron#24]
Good day,

i'm trying to set up a chart widget for the number of errors reported per hour for the last 24 hours. 

I've set up a chart widget and pointed it to a data source with the following splunk query:
Environment="Production" Level="ERROR" |bucket _time span=1h | stats count by _time

This leads to an empty chart widget, with a javascript error logged to the console pointing to highchart errors #14: String value sent to series.data, expected Number ( https://www.highcharts.com/errors/14 )

I feel like what I'm doing is rather basic - how can I fix this? I 'm pretty sure the count values returned form the query are actually numbers.

**Comment by baumandm** [comment]
Hi @JoachimL, it has been a while since I used the Splunk API, so I can't remember if I've had this issue before.  Based on the error, it must be returning strings from the Splunk API.  I checked the Cyclotron code, and there's nothing to convert data types&mdash;the Splunk REST API doesn't provide column type information either.  I also checked the Splunk documentation, and didn't see any relevant options or anything else related to this.

I don't currently have access to a Splunk environment to verify the API responses (on vacation), but here's an easy solution for you.  You can add the Post-Processor function to your Data Source, and use that to convert any numerical columns:

    pp = function (data) {
        return _.map(data, function (row) {
            row.count = parseInt(row.count, 10);
            return row;
        });
    }

Here I'm using parseInt() on the count column, but you could extend to any other columns you want to transform (or parseFloat(), etc).
