### ISSUE TITLE
Cyclotron-site doesn't work with node 7

### ISSUE THREAD

**Issue by frankh** [ExpediaInceCommercePlatform/cyclotron#3]
This deprecation warning in node 6:

`DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.`

Is an error in node 7

edit: Also the api seems to hang on /tags in node 7, but works fine in 6

**Comment by baumandm** [comment]
Hey @frankh, the cyclotron-site build issue should be fixed now with an upgrade to Karma.

As far as the API hanging, I quickly tested upgrading Mongoose `"mongoose": "~4.5.1",` and it seemed to fix the problem on Node 7.x.  But since it's a major version upgrade, we'll have to check the changelog and do more exhaustive testing to ensure nothing breaks.  You can upgrade it manually for now, and I'll try to get it verified and pushed out in our next release.
