### ISSUE TITLE
Dependency of event-stream@3.3.6 causes failure

### ISSUE THREAD

**Issue by eercanayar** [ExpediaInceCommercePlatform/cyclotron#37]
`cyclotron-site/package.json` requires `event-stream@3.3.6` indirectly and this package is suspended because of a security vulnerability. You can have a look at [npm blog](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident). How can we solve this dependency problem? It causes failure when `npm install` is run.

```
MacBook-Pro:cyclotron-site $ sudo npm install
npm ERR! code E404
npm ERR! 404 Not Found: event-stream@3.3.6

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/.npm/_logs/2018-12-10T12_27_08_401Z-debug.log
```

**Comment by pratiks** [comment]
This was the package that made news a while back that had the security vulnerability, it was removed from npm. It was since fixed.

 See here:  https://github.com/dominictarr/event-stream/issues/116.

Removing the package-lock.json and running npm install will update your dependencies with the new version.

**Comment by pratiks** [comment]
@baumandm  - I can submit a PR, would you prefer an update to only the single dependency?

**Comment by baumandm** [comment]
That would be great!  Probably safer to include the entire `package-lock.json`.
